#  Manipulação de Dados com Pandas: Analisa Json
Este notebook registra o aprendizado de fundamentos da biblioteca **Pandas**
---

In [2]:
import pandas as pd

In [3]:
df = pd.read_json(r"D:\Area de trabalho\Data-Science-Learning\02-Python\Base-de-dados\receitas.json",encoding="utf-8")
df

                                             Receita
0  {'Titulo': 'Bolo de Chocolate', 'Tempo de Prep...
1  {'Titulo': 'Bolo de Cenoura', 'Tempo de Prepar...

In [ ]:
receitas_expandidas = []

for receita in df['Receita']:
    total_ingredientes = len(receita['Ingredientes'])
    receitas_info = {
        'Titulo': receita['Titulo'],
        'Tempo de Preparo': receita['Tempo de Preparo'],
        'Porções': receita['Porções'],
        'Total de Ingredientes': total_ingredientes
    }
    receitas_expandidas.append(receitas_info)

print(len(receitas_expandidas)) 
df_expandido = pd.DataFrame(receitas_expandidas)
df_expandido

2

              Titulo Tempo de Preparo    Porções  Total de Ingredientes
0  Bolo de Chocolate       45 minutos  8 porções                     10
1    Bolo de Cenoura       40 minutos  4 porções                      6