#  Manipulação de Dados com Pandas: Importa Json
Este notebook registra o aprendizado de fundamentos da biblioteca **Pandas**
---

In [1]:
import pandas as pd

In [15]:
df = pd.read_json(r"D:\Area de trabalho\Data-Science-Learning\02-Python\Base-de-dados\receitas.json",encoding="utf-8")
df

                                             Receita
0  {'Titulo': 'Bolo de Chocolate', 'Tempo de Prep...
1  {'Titulo': 'Bolo de Cenoura', 'Tempo de Prepar...

In [18]:
df_receitas = pd.json_normalize(
    df['Receita'],
    record_path='Ingredientes',
    meta=['Titulo', 'Tempo de Preparo', 'Porções']
)
df_receitas

,0,Titulo,Tempo de Preparo,Porções
0,2 xícaras de farinha de trigo,Bolo de Chocolate,45 minutos,8 porções
0,1 xícara de açúcar,Bolo de Chocolate,45 minutos,8 porções
0,1 xícara de cacau em pó,Bolo de Chocolate,45 minutos,8 porções
0,1 colher de chá de fermento em pó,Bolo de Chocolate,45 minutos,8 porções
0,1/2 colher de chá de bicarbonato de sódio,Bolo de Chocolate,45 minutos,8 porções
0,1/2 colher de chá de sal,Bolo de Chocolate,45 minutos,8 porções
0,1 xícara de leite,Bolo de Chocolate,45 minutos,8 porções
0,1/2 xícara de óleo vegetal,Bolo de Chocolate,45 minutos,8 porções
0,2 ovos,Bolo de Chocolate,45 minutos,8 porções
0,1 colher de chá de essência de baunilha,Bolo de Chocolate,45 minutos,8 porções
1,3 cenouras médias raladas,Bolo de Cenoura,40 minutos,4 porções
1,4 ovos,Bolo de Cenoura,40 minutos,4 porções
1,1 xícara de óleo vegetal,Bolo de Cenoura,40 minutos,4 porções
1,2 xícaras de açúcar,Bolo de Cenoura,40 minutos,4 porções
1,2 e 1/2 xícaras de farinha de trigo,Bolo de Cenoura,40 minutos,4 porções
1,1 colher de sopa de fermento em pó,Bolo de Cenoura,40 minutos,4 porções

NameError: name 'df_receitas' is not defined