# Pandas: Groupby, agg, merge, transform

---

Limpar o dataset 
usando `groupby`, `agg`, `merge` e `transform`.

---

## 📚 Conceitos praticados

- `groupby` + `agg` — agregar métricas
- `transform` — criar colunas relativas sem perder o índice original
- `merge` — cruzar tabelas 
- Limpeza: tipos, nulos, padronização de nomes

In [48]:
import pandas as pd
import numpy as np

In [49]:
# Carregando Arquivos

df = pd.read_csv('D:/Area de trabalho/Data-Science-Learning/02-Python/Base-de-dados/Google_Ads_Dataset.csv')

# 1. Exploração - EDA
---
Funções como .sample(), .info(), .describe(), e .duplicated() ajudam a ter uma visão geral dos dados!!

In [50]:
# Recolhendo Amostras

df.sample(10)

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
2474,A3474,DeepLearnngPro,80.0,3836.0,$209.37,20.0,7.0,NaN,$1937,28-11-2024,dheli,TABLET,online data analytic
974,A1974,Webdevmastery,126.0,4670.0,$234.65,25.0,8.0,NaN,$1470,2024/11/23,madras,DESKTOP,online data analytic
2547,A3547,dATAsCIENCEbOOTCAMP,101.0,5983.0,$185.86,10.0,5.0,0.050,$1019,06-11-2024,Bombay,tablet,online data analytic
224,A1224,D@taScienceBootcamp,132.0,4490.0,$202.45,10.0,7.0,0.053,$1441,2024-11-10,delhi,mobile,data analitics online
1409,A2409,ai_mARKETING101,175.0,5720.0,$243.8,17.0,6.0,NaN,NaN,2024-11-26,mumbai,desktop,data analitics online
1797,A2797,D3epLearnngPro,189.0,3029.0,NaN,21.0,3.0,0.016,$1016,2024/11/05,Benglore,DESKTOP,data anaytics training
1322,A2322,wEBdEVmASTERY,96.0,3730.0,$217.61,16.0,4.0,0.042,$1283,2024-11-07,CHENNAI,Desktop,analytics for data
455,A1455,pYTHON4dATA,114.0,4804.0,$249.33,14.0,6.0,0.053,$1879,05-11-2024,chenay,mobile,data analytics course
849,A1849,wEBdEVmASTERY,193.0,5899.0,$227.24,12.0,9.0,0.042,$1832,02-11-2024,delhi,desktop,analytics for data
546,A1546,CyberSecurtyFundamentals,132.0,3365.0,$198.01,17.0,9.0,0.068,$1161,2024/11/14,Bombay,DESKTOP,analytics for data

In [51]:
# Sumario dos dados

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   object
 1   Campaign_Name    2600 non-null   object
 2   Clicks           2488 non-null   float64
 3   Impressions      2546 non-null   float64
 4   Cost             2503 non-null   object
 5   Leads            2552 non-null   float64
 6   Conversions      2526 non-null   float64
 7   Conversion Rate  1974 non-null   float64
 8   Sale_Amount      2461 non-null   object
 9   Ad_Date          2600 non-null   object
 10  Location         2600 non-null   object
 11  Device           2600 non-null   object
 12  Keyword          2600 non-null   object
dtypes: float64(5), object(8)
memory usage: 264.2+ KB

In [52]:
# Estatistica descritivas
df.describe()

            Clicks  Impressions        Leads  Conversions  Conversion Rate
count  2488.000000  2546.000000  2552.000000  2526.000000      1974.000000
mean    138.956994  4523.280833    20.003918     6.519002         0.048979
std      34.619376   869.927913     6.032317     2.272573         0.019987
min      80.000000  3000.000000    10.000000     3.000000         0.015000
25%     110.000000  3764.000000    15.000000     5.000000         0.035000
50%     139.000000  4518.500000    20.000000     7.000000         0.046000
75%     169.000000  5279.500000    25.000000     9.000000         0.058000
max     199.000000  5999.000000    30.000000    10.000000         0.123000

In [53]:
# Linhas duplicadas
df.duplicated().sum()

np.int64(0)

#2. Polimento
---


- Etapas como padronização e correção de inconsistencias nos dados;
- Expressões regulares (RegEx) podem ser muito uteis para manupulação de texto.

In [54]:
# Utilizando RegEx
df[["Cost","Sale_Amount"]] = df[["Cost","Sale_Amount"]].replace("[^0-9.]", "", regex=True).astype(float)

In [55]:
# Correção de inconsistências em location

df["Location"] = df["Location"].str.lower()

ajustar = {
    "bengluru": "Bangalore",
    "benglore": "Bangalore",
    "bangalore": "Bangalore",
    "bengaluru": "Bangalore",
    "mumbay": "Mumbai",
    "mumabi": "Mumbai",
    "mumbai": "Mumbai",
    "bombay": "Mumbai",
    "dheli": "Delhi",
    "delhi": "Delhi",
    "newdlhi": "New Delhi",
    "new delhi": "New Delhi",
    "chnnai": "Chennai",
    "madras": "Chennai",
    "chenay": "Chennai",
    "chennai": "Chennai",
    "poona": "Pune",
    "punea": "Pune",
    "punr": "Pune",
    "pune": "Pune"
}

df["Location"] = df["Location"].replace(ajustar)

In [56]:
# Correção de inconsistências em Device
# Ex: "MOBILE", "mobile", "Mobile" → "Mobile"
df["Device"] = df["Device"].str.capitalize()

In [57]:
#Checagem
print(df["Location"].unique())
print(df["Device"].unique())

['Pune' 'New Delhi' 'Mumbai' 'Delhi' 'Chennai' 'Bangalore']
['Desktop' 'Mobile' 'Tablet']

In [58]:
# Ajustando oformato de datas

df["Ad_Date"] = pd.to_datetime(df["Ad_Date"], format = "mixed", dayfirst=True)

In [59]:
# Checagem final
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,CyberSecurtyFundamentals,104.0,4498.0,231.88,14.0,7.0,0.058,1892.0,2024-11-16,Pune,Desktop,learn data analytics
1,A1001,SQLDatabseTraining,173.0,5107.0,216.84,10.0,8.0,0.046,1679.0,2024-11-20,New Delhi,Mobile,data analytics course
2,A1002,Python4D@ta,90.0,4544.0,203.66,26.0,9.0,NaN,1624.0,2024-11-16,Pune,Desktop,data analitics online
3,A1003,AI_Marketing1011,142.0,3185.0,237.66,17.0,6.0,NaN,1225.0,2024-11-26,Mumbai,Tablet,data anaytics training
4,A1004,SQLDatabseTraining1,156.0,3361.0,195.90,30.0,8.0,NaN,1091.0,2024-11-22,Mumbai,Desktop,online data analytic

# Anomalias
---

- Na grande maioria dos casos, serão *missing values* e *outliers*;

## 3.1 Lidando com *Missing Values*

1º Verificar se estes dados não podem ser recuperados;  
2º Como estão apresentados no *dataset*? Ex: célula vazia, NaN, ??, #, -...  
3º Identificar qual o tipo do dado faltante;  
4º Definir o que vai ser feito:

- Drop de dados;
- Imputação de estatística simples → média ou mediana (global ou estratificada), imputação por regra...
- Imputação avançada com *Machine Learning* → imputação múltipla (MICE) ou KNN

In [60]:
# Identificando a distribuição de missing values
# Em Porcentagem
(df.isnull().sum() * 100/df.index.size).round(2).sort_values(ascending=False) # e porcentagem

Conversion Rate    24.08
Sale_Amount         5.35
Clicks              4.31
Cost                3.73
Conversions         2.85
Impressions         2.08
Leads               1.85
Campaign_Name       0.00
Ad_ID               0.00
Ad_Date             0.00
Location            0.00
Device              0.00
Keyword             0.00
dtype: float64

é possivel calcular o conversion rae a partir da seguinte formula:

CR = conversions / clicks * 100

In [61]:
# Imputação por regra

# 1. Calcula Conversion Rate a partir de Conversions e Clicks
filtro_1 = df["Conversion Rate"].isna() & df["Clicks"].notna() & df["Conversions"].notna()
df.loc[filtro_1, "Conversion Rate"] = df["Conversions"] / df["Clicks"]

# 2. Calcula Conversions a partir de Conversion Rate e Clicks
filtro_2 = df["Conversions"].isna() & df["Clicks"].notna() & df["Conversion Rate"].notna()
df.loc[filtro_2, "Conversions"] = df["Clicks"] * df["Conversion Rate"]

# 3. Calcula Clicks a partir de Conversions e Conversion Rate
filtro_3 = df["Clicks"].isna() & df["Conversions"].notna() & df["Conversion Rate"].notna()
df.loc[filtro_3, "Clicks"] = df["Conversions"] / df["Conversion Rate"]

In [62]:
# Revisando os valores de missing values após a imputação
(df.isnull().sum() * 100/df.index.size).round(2).sort_values(ascending=False) # em porcentagem

Conversion Rate    5.88
Sale_Amount        5.35
Cost               3.73
Clicks             3.58
Conversions        2.42
Impressions        2.08
Leads              1.85
Campaign_Name      0.00
Ad_ID              0.00
Ad_Date            0.00
Location           0.00
Device             0.00
Keyword            0.00
dtype: float64

In [63]:
# Imputação estratificada
df_imputado = df.copy()

# Variáveis que possuem faltantes
variaveis = ["Conversion Rate", "Conversions", "Clicks", "Sale_Amount", "Impressions", "Leads", "Cost"]

for var in variaveis:
    df_imputado[var] = df_imputado.groupby(["Location", "Device"])[var].transform(lambda x: x.fillna(x.median()))

(df_imputado.isnull().sum() * 100 / df_imputado.index.size).round(2).sort_values(ascending=False)

Ad_ID              0.0
Campaign_Name      0.0
Clicks             0.0
Impressions        0.0
Cost               0.0
Leads              0.0
Conversions        0.0
Conversion Rate    0.0
Sale_Amount        0.0
Ad_Date            0.0
Location           0.0
Device             0.0
Keyword            0.0
dtype: float64

In [64]:
# Identificação de outliers com IQR  (Interquartile Range) é a distância entre o 1º e o 3º quartil dos dados, ou seja, representa os 50% centrais da distribuição.
# Qualquer valor abaixo de Q1 - 1.5 * IQR ou acima de Q3 + 1.5 * IQR é considerado um outlier.

outliers = {}

# Filtragem por IQR
for col in df_imputado.select_dtypes(include=["float64", "int64"]).columns:
    Q1 = df_imputado[col].quantile(0.25)
    Q3 = df_imputado[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    filtro = (df_imputado[col] < limite_inferior) | (df_imputado[col] > limite_superior)
    count = filtro.sum()

    # Contagem de Outliers por coluna
    if count > 0:
        menor_valor = df_imputado.loc[filtro, col].min()
        maior_valor = df_imputado.loc[filtro, col].max()
    else:
        maior_valor = None
        menor_valor = None

    # Construindo um dataframe com os Outliers encontrados
    outliers[col] = {
        "Contagem de Outliers": count,
        "% de Outliers": ((count / len(df_imputado)) * 100).round(3),
        "Limite Inferior": limite_inferior.round(3),
        "Limite Superior": limite_superior.round(3),
        "Menor outlier": maior_valor,
        "Maior outlier": menor_valor
    }

outlier_df = pd.DataFrame.from_dict(outliers, orient="index")
outlier_df.head()

,Contagem de Outliers,% de Outliers,Limite Inferior,Limite Superior,Menor outlier,Maior outlier
Clicks,2,0.077,25.500,253.500,322.580645,303.030303
Impressions,0,0.000,1542.625,7503.625,NaN,NaN
Cost,0,0.000,147.516,283.166,NaN,NaN
Leads,0,0.000,0.000,40.000,NaN,NaN
Conversions,0,0.000,0.500,12.500,NaN,NaN

In [65]:
# Passo opcional - Winsorização de Outliers
winsor_df = df_imputado.copy()

for col in winsor_df.select_dtypes(include=["float64", "int64"]).columns:
    Q1 = winsor_df[col].quantile(0.25)
    Q3 = winsor_df[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    # Winsorização manual (apenas se houver outliers)
    winsor_df[col] = winsor_df[col].apply(
        lambda x: limite_inferior if x < limite_inferior else limite_superior if x > limite_superior else x
    )

In [66]:
# Chegagem
winsor_df.describe()

,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date
count,2600.000000,2600.000000,2600.000000,2600.000000,2600.000000,2600.000000,2600.000000,2600
mean,139.023200,4523.495962,215.094819,20.005000,6.523389,0.048730,1498.825577,2024-11-15 16:54:38.769230848
min,60.000000,3000.000000,180.010000,10.000000,3.000000,0.015000,1000.000000,2024-11-01 00:00:00
25%,111.000000,3778.000000,198.385000,15.000000,5.000000,0.035852,1262.000000,2024-11-08 00:00:00
50%,139.000000,4524.000000,215.600000,20.000000,7.000000,0.047000,1500.500000,2024-11-16 00:00:00
75%,168.000000,5268.250000,232.297500,25.000000,8.000000,0.058000,1728.000000,2024-11-23 00:00:00
max,253.500000,5999.000000,249.890000,30.000000,10.000000,0.091223,2000.000000,2024-11-30 00:00:00
std,34.287568,861.073432,19.917166,5.976723,2.245082,0.018523,279.405020,NaN

#4. Finalização

---

In [67]:
winsor_df.to_csv('D:/Area de trabalho/Data-Science-Learning/02-Python/Base-de-dados/Google_Ads_Dataset_Limpo.csv', index=False)

## O que foi feito

- **EDA inicial:** `sample()`, `info()`, `describe()` e checagem de duplicatas;
- **Polimento:** padronização de `Device` e correção de inconsistências em `Location`;
- **Missing Values:** imputação por regra (relação entre colunas) e imputação estratificada por `Location` e `Device`;
- **Outliers:** identificação via IQR e winsorização dos valores extremos.

## Aprendizados

- Dados reais chegam sujos — padronização de texto é sempre o primeiro passo;
- Imputação estratificada é mais inteligente que usar a média global;
- Winsorização preserva os dados sem simplesmente deletar outliers.