# Pandas: Groupby, agg, merge, transform

---

Limpar o dataset 
usando `groupby`, `agg`, `merge` e `transform`.

---

## 📚 Conceitos praticados

- `groupby` + `agg` — agregar métricas
- `transform` — criar colunas relativas sem perder o índice original
- `merge` — cruzar tabelas 
- Limpeza: tipos, nulos, padronização de nomes

In [23]:
import pandas as pd
import numpy as np

In [25]:
# Carregando Arquivos

df = pd.read_csv('D:/Area de trabalho/Data-Science-Learning/02-Python/Base-de-dados/Google_Ads_Dataset.csv')

# 1. Exploração - EDA
---
Funções como .sample(), .info(), .describe(), e .duplicated() ajudam a ter uma visão geral dos dados!!

In [27]:
# Recolhendo Amostras

df.sample(10)

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
1068,A2068,SQLDatabs3Training,81.0,5653.0,$245.33,23.0,8.0,0.099,$1248,2024-11-26,punea,Mobile,data analitics online
2513,A3513,Python4Data_,193.0,3978.0,$231.8,20.0,3.0,0.046,$1126,2024/11/16,MUMBAI,Mobile,online data analytic
1573,A2573,Businessanlyticsclass,123.0,3860.0,$224.63,24.0,8.0,0.065,$1800,2024-11-15,BANGALORE,DESKTOP,analytics for data
1938,A2938,DataScienceB0otcamp,130.0,4393.0,$198.66,19.0,7.0,0.054,$1236,2024/11/11,mumabi,desktop,data analitics online
414,A1414,BusinessAnlyticsClass_,99.0,4040.0,NaN,13.0,5.0,0.051,$1502,2024-11-26,chenay,tablet,online data analytic
1920,A2920,Python4D@ta,133.0,4116.0,$248.26,14.0,3.0,0.033,$1160,2024/11/20,Bombay,Mobile,data analytics course
597,A1597,CyberSecurtyFund@mentals,196.0,5386.0,$224.31,23.0,4.0,0.020,$1423,2024/11/30,chennai,tablet,learn data analytics
2211,A3211,MachneLearningBasics,96.0,5210.0,$223.05,10.0,8.0,0.083,$1483,2024-11-29,MUMBAI,tablet,online data analytic
882,A1882,DeepLearnngPr0,110.0,4542.0,$227.95,20.0,4.0,0.036,$1423,2024/11/11,mumabi,desktop,data anaytics training
173,A1173,DeepLe@rnngPro,170.0,4519.0,$240.63,22.0,7.0,0.041,$1012,27-11-2024,madras,MOBILE,analytics for data

In [ ]:
# Sumario dos dados

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ad_ID            2600 non-null   object
 1   Campaign_Name    2600 non-null   object
 2   Clicks           2488 non-null   float64
 3   Impressions      2546 non-null   float64
 4   Cost             2503 non-null   object
 5   Leads            2552 non-null   float64
 6   Conversions      2526 non-null   float64
 7   Conversion Rate  1974 non-null   float64
 8   Sale_Amount      2461 non-null   object
 9   Ad_Date          2600 non-null   object
 10  Location         2600 non-null   object
 11  Device           2600 non-null   object
 12  Keyword          2600 non-null   object
dtypes: float64(5), object(8)
memory usage: 264.2+ KB

In [29]:
# Estatistica descritivas
df.describe()

            Clicks  Impressions        Leads  Conversions  Conversion Rate
count  2488.000000  2546.000000  2552.000000  2526.000000      1974.000000
mean    138.956994  4523.280833    20.003918     6.519002         0.048979
std      34.619376   869.927913     6.032317     2.272573         0.019987
min      80.000000  3000.000000    10.000000     3.000000         0.015000
25%     110.000000  3764.000000    15.000000     5.000000         0.035000
50%     139.000000  4518.500000    20.000000     7.000000         0.046000
75%     169.000000  5279.500000    25.000000     9.000000         0.058000
max     199.000000  5999.000000    30.000000    10.000000         0.123000

In [30]:
# Linhas duplicadas
df.duplicated().sum()

np.int64(0)

#2. Polimento
---


- Etapas como padronização e correção de inconsistencias nos dados;
- Expressões regulares (RegEx) podem ser muito uteis para manupulação de texto.

In [ ]:
# Utilizando RegEx
df[["Cost","Sale_Amount"]] = df[["Cost","Sale_Amount"]].replace('[\$,]', '', regex=True).astype(float)