# Amostragem

In [3]:
import pandas as pd
import random
import numpy as np

## Carregando Base de dados

In [4]:
dataset = pd.read_csv(r'D:/Area de trabalho/Data-Science-Learning/03-Estatistica/Base de dados/census.csv')

In [5]:
dataset.shape #  retorna as dimensões do  DataFrame no formato (linhas, colunas)

(32561, 15)

In [6]:
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Amostragem aleatória simples

In [8]:
# Amostra aleatória simples de 100 registros do dataset
df_amostra_aleatorioa_simples = dataset.sample(n=100)

In [9]:
df_amostra_aleatorioa_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
19471,22,Private,136767,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,United-States,<=50K
20322,33,Private,69311,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
6932,37,Local-gov,333664,Some-college,10,Separated,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
6519,51,Self-emp-not-inc,165001,Masters,14,Divorced,Exec-managerial,Unmarried,White,Male,25236,0,50,United-States,>50K
10159,54,Private,98535,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [10]:
# Amostragem aleatória simples | Parâmetros: dataset, quantidade de amostras
def amostragem_aleatoria_simples(dataset, amostras):
    return dataset.sample(n = amostras)

In [11]:
df_amostra_aleatorioa_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatorioa_simples.shape

(100, 15)

In [12]:
df_amostra_aleatorioa_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
20243,37,Private,109133,Masters,14,Separated,Exec-managerial,Not-in-family,White,Male,27828,0,60,Iran,>50K
15960,65,?,198019,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,0,35,United-States,<=50K
10921,23,Private,235853,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
4459,37,State-gov,46814,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,38,United-States,<=50K
2433,42,State-gov,293791,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K

## Amostragem sistemática

In [13]:
dataset.shape

(32561, 15)

In [14]:
len(dataset) // 100 # Retorna o tamanho do Dataset / 100

325

In [15]:
random.seed(1)
random.randint(0, 325) # Sempre retorna o mesmo número

68

In [16]:
# Gera uma sequencia de numerosc comaçando em 68  e indo até o final do dataset e pula de 325 em 325
np.arange(68, len(dataset), step = 325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [17]:
# Amostragem sistemática | Seleciona linhas em intervalos regulares com início aleatório
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(dataset),step = intervalo)
    amostragem_sistematica = dataset.iloc[indices]
    return amostragem_sistematica

In [18]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100 )
df_amostra_aleatorioa_simples.shape

(100, 15)

In [19]:
df_amostra_sistematica.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
68,49,Self-emp-inc,191681,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
393,34,State-gov,98101,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,45,?,>50K
718,22,Private,214399,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,<=50K
1043,44,Private,167005,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,60,United-States,>50K
1368,52,Private,152234,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,99999,0,40,Japan,>50K

## Amostragem por grupos

In [20]:
len(dataset) / 10

3256.1

In [21]:
grupos = []
id_grupo = 0
contagem = 0
LIMITE_GRUPO = 3256  # constante nomeada

for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > LIMITE_GRUPO:
        contagem = 0
        id_grupo += 1

# Resumo dos grupos criados
grupos_unicos, contagens = np.unique(grupos, return_counts=True)

print(f"Total de grupos criados: {id_grupo + 1}")
print(f" Linhas por grupo: {contagens}")
print(f" Total de linhas processadas: {len(grupos)}")

Total de grupos criados: 10
 Linhas por grupo: [3257 3257 3257 3257 3257 3257 3257 3257 3257 3248]
 Total de linhas processadas: 32561

In [22]:
# Verifica quantos grupos foram criados e quantas linhas cada um tem
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [23]:
# compara o tamanho da lista de grupos com o shape do dataset
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [24]:
dataset['Grupo'] = grupos

In [25]:
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,Grupo
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0

In [26]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,Grupo
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,9
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,9
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,9
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,9
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,9

In [27]:
random.randint(0, 9)

9

In [28]:
df_agrupamento = dataset[dataset['Grupo'] == 7]
df_agrupamento.shape

(3257, 16)

In [29]:
df_agrupamento['Grupo'].value_counts()

Grupo
7    3257
Name: count, dtype: int64

In [30]:
def amostragem_agrupamento(dataset, numero_grupos):
    intervalo = len(dataset) / numero_grupos  #
    grupos = []
    id_grupo = 0
    contagem = 0
    LIMITE_GRUPO = intervalo  

    for _ in dataset.iterrows():
        grupos.append(id_grupo)
        contagem += 1
        if contagem > LIMITE_GRUPO:
            contagem = 0
            id_grupo += 1

    dataset['Grupo'] = grupos
    grupo_selecionado = random.randint(0, numero_grupos - 1) 
    return dataset[dataset['Grupo'] == grupo_selecionado]

In [31]:
df_amostra_agrupamento = amostragem_agrupamento(dataset, 100)
df_amostra_agrupamento.shape, df_amostra_agrupamento['Grupo'].value_counts()

((326, 16),
 Grupo
 97    326
 Name: count, dtype: int64)

## Amostragem Estratificada

In [32]:
from sklearn.model_selection import StratifiedShuffleSplit

In [33]:
dataset['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [34]:
7841 / len(dataset), 24720 / len(dataset)

(0.2408095574460244, 0.7591904425539756)

In [35]:
100 / len(dataset)

0.0030711587481956942

In [36]:
split = StratifiedShuffleSplit(test_size=0.0030711587481956942)
for x, y in split.split(dataset, dataset['income']):
    df_x = dataset.iloc[x]
    df_y = dataset.iloc[y]

In [37]:
df_x.shape, df_y.shape

((32461, 16), (100, 16))

In [38]:
df_y.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,Grupo
14137,19,Local-gov,53220,HS-grad,9,Never-married,Adm-clerical,Own-child,Black,Female,0,0,40,United-States,<=50K,43
25942,38,Private,299810,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,79
14150,69,Self-emp-not-inc,349022,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,33,United-States,<=50K,43
20598,41,Private,58880,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,White,Female,7688,0,10,United-States,>50K,63
8543,62,?,191188,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,<=50K,26

In [39]:
df_y['income'].value_counts()

income
<=50K    76
>50K     24
Name: count, dtype: int64

In [40]:
def amostragem_estratificada(dataset, percentual):
    split = StratifiedShuffleSplit(test_size=percentual, random_state=1)
    for x, y in split.split(dataset, dataset['income']):
        df_x = dataset.iloc[x]
        df_y = dataset.iloc[y]
    return df_y

In [41]:
df_amostra_estratificada = amostragem_estratificada(dataset, 0.0030711587481956942)
df_amostra_estratificada.shape

(100, 16)

## Amostragem de reservatório

In [42]:
stream = []
for i in range(len(dataset)):
    stream.append(dataset.iloc[i])

In [43]:
def amostragem_reservatorio(dataset, amostras):
    stream = []
    
    for i in range(len(dataset)):
        stream.append(i)

    i = 0
    tamanho = len(dataset)

    reservatorio = [0] * amostras

    for i in range(amostras):
        reservatorio[i] = stream[i]

    while i < tamanho:
        j = random.randrange(i + 1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i += 1

    return dataset.iloc[reservatorio]

In [44]:
df_amostragem_reservatorio = amostragem_reservatorio(dataset, 100)
df_amostragem_reservatorio.shape

(100, 16)

In [45]:
df_amostragem_reservatorio.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income,Grupo
29608,41,Self-emp-inc,114580,Prof-school,15,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,2415,55,United-States,>50K,90
21696,37,Federal-gov,329088,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,Black,Male,0,0,40,United-States,<=50K,66
30676,42,Private,355728,Assoc-voc,11,Never-married,Craft-repair,Not-in-family,White,Male,0,0,44,United-States,<=50K,94
28550,43,Private,110970,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,40,United-States,>50K,87
8768,52,Federal-gov,221532,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,45,United-States,>50K,26

# Comparativo dos resultado

In [46]:
dataset['age'].mean()

np.float64(38.58164675532078)

In [47]:
df_amostra_aleatorioa_simples['age'].mean()

np.float64(37.54)

In [48]:
df_amostra_sistematica['age'].mean()

np.float64(37.57)

In [49]:
df_amostra_agrupamento['age'].mean()

np.float64(40.38957055214724)

In [50]:
df_amostra_estratificada['age'].mean()

np.float64(36.9)

In [51]:
df_amostragem_reservatorio['age'].mean()

np.float64(37.85)