# Amostragem

In [1]:
import pandas as pd
import random
import numpy as np

## Carregando Base de dados

In [4]:
dataset = pd.read_csv(r'D:\Area de trabalho\Data-Science-Learning\03-Estatistica\base de dados\census.csv')

In [ ]:
dataset.shape #  retorna as dimensões do  DataFrame no formato (linhas, colunas)

(32561, 15)

In [6]:
dataset.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
dataset.tail()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Amostragem aleatória simples

In [14]:
# Amostra aleatória simples de 100 registros do dataset
df_amostra_aleatorioa_simples = dataset.sample(n=100)

In [15]:
df_amostra_aleatorioa_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
24714,18,?,172214,HS-grad,9,Never-married,?,Own-child,Black,Female,0,0,20,United-States,<=50K
14853,36,Private,398931,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K
12444,34,Private,183778,HS-grad,9,Divorced,Transport-moving,Not-in-family,White,Male,0,0,40,United-States,<=50K
23881,17,Private,178953,12th,8,Never-married,Sales,Own-child,White,Female,0,0,20,United-States,<=50K
24889,42,Private,245565,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Female,0,0,12,England,<=50K

In [27]:
# Amostragem aleatória simples | Parâmetros: dataset, quantidade de amostras
def amostragem_aleatoria_simples(dataset, amostras):
    return dataset.sample(n = amostras)

In [28]:
df_amostra_aleatorioa_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatorioa_simples.shape

(100, 15)

In [29]:
df_amostra_aleatorioa_simples.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
17847,26,Private,41521,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,35,United-States,<=50K
27400,35,Private,82622,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,40,United-States,<=50K
11660,45,Federal-gov,155659,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
15249,41,Private,282882,HS-grad,9,Never-married,Sales,Unmarried,Black,Female,0,0,40,United-States,<=50K
23247,25,Private,148460,HS-grad,9,Never-married,Adm-clerical,Own-child,Black,Female,4416,0,40,Puerto-Rico,<=50K